<a href="https://colab.research.google.com/github/Mahak-Tech-05/Advance-Python-13-days-series/blob/main/day-24/p_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# ==============================
# 📊 STUDENT DATA ANALYSIS PROJECT
# ==============================

import pandas as pd

# ---- Step 1: Create Data ----
data = {
    "Name": ["Ram", "Basanti", "Thakur", "Gita", "Shamelal"],
    "Marks": [85, 90, None, 40, 75],
    "Age": [20, 21, 19, 18, None]
}

df = pd.DataFrame(data)

print("----- Original Data -----")
display(df)   # better than print in Colab

# ---- Step 2: Data Cleaning ----
df["Marks"] = df["Marks"].fillna(df["Marks"].mean().round(2))
df["Age"] = df["Age"].fillna(df["Age"].mean().round(0))

print("\n----- After Cleaning -----")
display(df)

# ---- Step 3: Basic Analysis ----
print("\n----- Analysis -----")
print("Average Marks:", df["Marks"].mean().round(2))
print("Maximum Marks:", df["Marks"].max())
print("Minimum Marks:", df["Marks"].min())

# ---- Step 4: Result Column ----
df["Result"] = df["Marks"].apply(lambda x: "Pass" if x >= 50 else "Fail")

# ---- Step 5: Grade System (Advanced) ----
def grade(marks):
    if marks >= 80:
        return "A"
    elif marks >= 60:
        return "B"
    elif marks >= 50:
        return "C"
    else:
        return "F"

df["Grade"] = df["Marks"].apply(grade)

print("\n----- Final Data with Result & Grade -----")
display(df)

# ---- Step 6: Filter Passed Students ----
passed_students = df[df["Result"] == "Pass"]

print("\n----- Students Who Passed -----")
display(passed_students)

# ---- Step 7: Save to CSV ----
file_name = "student_output.csv"
df.to_csv(file_name, index=False)

print("\n✅ Data saved to", file_name)

# ---- Step 8: Download File (Colab only) ----
from google.colab import files
files.download(file_name)

----- Original Data -----

       Name  Marks   Age
0       Ram   85.0  20.0
1   Basanti   90.0  21.0
2    Thakur    NaN  19.0
3      Gita   40.0  18.0
4  Shamelal   75.0   NaN

----- After Cleaning -----

       Name  Marks   Age
0       Ram   85.0  20.0
1   Basanti   90.0  21.0
2    Thakur   72.5  19.0
3      Gita   40.0  18.0
4  Shamelal   75.0  20.0

----- Analysis -----
Average Marks: 72.5
Maximum Marks: 90.0
Minimum Marks: 40.0

----- Final Data with Result & Grade -----

       Name  Marks   Age Result Grade
0       Ram   85.0  20.0   Pass     A
1   Basanti   90.0  21.0   Pass     A
2    Thakur   72.5  19.0   Pass     B
3      Gita   40.0  18.0   Fail     F
4  Shamelal   75.0  20.0   Pass     B

----- Students Who Passed -----

       Name  Marks   Age Result Grade
0       Ram   85.0  20.0   Pass     A
1   Basanti   90.0  21.0   Pass     A
2    Thakur   72.5  19.0   Pass     B
4  Shamelal   75.0  20.0   Pass     B

✅ Data saved to student_output.csv